### ISSUE TITLE
部署请教

### ISSUE THREAD

**Issue by xiaozhaha** [code-gyu/wxPushWeather#1]
请问下老哥，如果我想本地部署的话，我怎么添加配置文件啥的啊，我想本地先跑通了，调整好模版啥的了，再用actions跑。

**Comment by code-gyu** [comment]
可以直接将main.py的那些变量写固定的;
比如：
# 呢称
name = os.environ['NAME']
更改成
name = "某某某"

**Comment by code-gyu** [comment]
已解决
